FROM node:22.16.0

WORKDIR /frontend

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port
EXPOSE 5173

# Command to run the frontend
CMD ["npm", "run", "dev"]
