"""change last used column nullable

Revision ID: 0090ff70bdf8
Revises: 03a571588e51
Create Date: 2025-05-26 21:56:04.638782

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "0090ff70bdf8"
down_revision: Union[str, None] = "03a571588e51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
