"""initial_schema

Revision ID: a0cfd46df880
Revises:
Create Date: 2025-05-26 13:57:40.579703

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a0cfd46df880"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
