"""Add handwriting fields to Essay

Revision ID: aa34664b3455
Revises: 65fbf7ac0f2a
Create Date: 2026-03-07 06:52:02.630051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

input_type_enum = sa.Enum('text', 'handwriting', name='inputtype')

# revision identifiers, used by Alembic.
revision: str = 'aa34664b3455'
down_revision: Union[str, None] = '65fbf7ac0f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    input_type_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'essays',
        sa.Column(
            'input_type',
            input_type_enum,
            server_default='text',
            nullable=False
        )
    )
    op.add_column('essays', sa.Column('image_path', sa.String(), nullable=True))
    op.add_column('essays', sa.Column('ocr_text', sa.Text(), nullable=True))
    op.alter_column('essays', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('essays', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('essays', 'ocr_text')
    op.drop_column('essays', 'image_path')
    op.drop_column('essays', 'input_type')

    input_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
