"""add api key name

Revision ID: aa406b2ebf58
Revises: d7f55738d45e
Create Date: 2025-05-26 19:08:07.592205

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa406b2ebf58"
down_revision: Union[str, None] = "d7f55738d45e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_api_keys", sa.Column("name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_api_keys", "name")
    # ### end Alembic commands ###
