"""last used add in api key table

Revision ID: bb8e68173f49
Revises: aa406b2ebf58
Create Date: 2025-05-26 21:53:10.639352

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb8e68173f49"
down_revision: Union[str, None] = "aa406b2ebf58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "user_api_keys",
        sa.Column(
            "last_used",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column("user_api_keys", "last_used", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_api_keys", "last_used")
    # ### end Alembic commands ###
