"""change the column names

Revision ID: d7f55738d45e
Revises: a0cfd46df880
Create Date: 2025-05-26 14:50:19.331280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d7f55738d45e"
down_revision: Union[str, None] = "a0cfd46df880"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ai_providers", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.add_column(
        "api_models",
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "user_api_keys",
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.drop_column("user_api_keys", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_api_keys",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("user_api_keys", "registered_at")
    op.drop_column("api_models", "registered_at")
    op.alter_column("ai_providers", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
