"""change api key name default function

Revision ID: e1ec562a03d9
Revises: 0090ff70bdf8
Create Date: 2025-05-26 22:06:22.031882

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e1ec562a03d9"
down_revision: Union[str, None] = "0090ff70bdf8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
