name: Build and Push to GHCR

on:
  workflow_run:
    workflows: [Test Backend]
    types: [completed]

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: production
      DOMAIN: ${{ secrets.DOMAIN_PRODUCTION }}
      VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL_PRODUCTION }}
      STACK_NAME: ${{ secrets.STACK_NAME_PRODUCTION }}
      SECRET_KEY: ${{ secrets.SECRET_KEY_PRODUCTION }}
      FIRST_SUPERUSER: ${{ secrets.FIRST_SUPERUSER_PRODUCTION }}
      FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD_PRODUCTION }}
      SMTP_HOST: ${{ secrets.SMTP_HOST_PRODUCTION }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME_PRODUCTION }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD_PRODUCTION }}
      EMAILS_FROM_EMAIL: ${{ secrets.EMAILS_FROM_EMAIL_PRODUCTION }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_PRODUCTION }}
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR with GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push images
        run: |
          # invalid reference format: repository name must be lowercase
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

          SERVICES=("backend" "frontend")

          for SERVICE in "${SERVICES[@]}"; do
            IMAGE_NAME="ghcr.io/${REPO_OWNER}/${SERVICE}:latest"
            echo "Building $SERVICE -> $IMAGE_NAME"
            docker build -t "$IMAGE_NAME" "./$SERVICE"
            docker push "$IMAGE_NAME"
          done
